magephp:
  log_dir: ./.mage
  environments:
    production:
      user: demo
      branch: dev
      from: ./
      host_path: /var/www/iwouldlike
      releases: 4
      exclude:
          - ./var/cache/*
          - ./var/log/*
      hosts:
          - 142.93.111.72
      pre-deploy:
          - 'App\Symfony\Command\Deploy\GitUpdate': { branch: 'dev' }
          - composer/install: { timeout: 3600 }
          - composer/dump-autoload
      post-deploy:
          - 'App\Symfony\Command\Deploy\CreateSymlink': { branch: 'dev' }