magephp:
  environments:
    production:
      log_dir: ./var/log
      user: root
      branch: dev
      from: ./
      host_path: /var/www
      releases: 4
      exclude:
          - ./var/cache/*
          - ./var/log/*
      hosts:
          - 142.93.111.72
      pre-deploy:
          - 'App\Symfony\Command\Deploy\GitUpdate': { branch: 'dev' }
          - composer/install: { timeout: 3600 }
          - composer/dump-autoload
      on-deploy:
          - symfony/cache-warmup: { env: 'prod' }
          - symfony/assets-install: { env: 'prod' }