magephp:
  log_dir: ./.mage
  environments:
    production:
      user: root
      branch: master
      from: ./
      host_path: /var/www/iwouldlike
      releases: 4
      exclude:
          - ./var/cache/*
          - ./var/log/*
      hosts:
          - 142.93.111.72
      pre-deploy:
          - 'App\Symfony\Command\Deploy\GitUpdate': { branch: 'master' }
          - composer/install: { timeout: 3600 }
          - composer/dump-autoload