app_static_index:
    path: /
    controller: App\Web\Controller\StaticController::getIndex

app_static_promise:
    path: /promise
    controller: App\Web\Controller\StaticController::getPromise

app_static_single_item:
    path: /item/{marketplace}/{title}/{itemId}
    controller: App\Web\Controller\StaticController::getSingleItem

app_static_search:
    path: /search
    controller: App\Web\Controller\StaticController::getSingleItem