app_static_index:
    path: /{_locale}
    controller: App\Web\Controller\StaticController::getIndex
    defaults:
        _locale: '%kernel.default_locale%'

app_static_single_item:
    path: /{_locale}/item/{title}/{itemId}
    controller: App\Web\Controller\StaticController::getSingleItem
    defaults:
        _locale: '%kernel.default_locale%'

app_static_search_temp:
    path: /{_locale}/search
    controller: App\Web\Controller\StaticController::getSearch
    defaults:
        _locale: '%kernel.default_locale%'

app_static_search:
    path: /{_locale}/search/{term}
    controller: App\Web\Controller\StaticController::getSearch
    defaults:
        _locale: '%kernel.default_locale%'