app_static:
    prefix: /
    resource: 'Static/'
    methods: [GET]
    host: goiwouldlike.com
    schemes: [http]
    type: directory
    requirements:
        _format: 'text/html'

app_dynamic:
    prefix: /api/v1
    resource: 'Dynamic'
    methods: [GET]
    host: goiwouldlike.com
    schemes: [http]
    type: directory
    requirements:
        _format: 'application/json'
