app_static:
    prefix: /
    resource: 'Static/'
    methods: [GET]
    host: iambuying.eu
    schemes: [http]
    type: directory
    requirements:
        _format: 'text/html'

app_dynamic:
    prefix: /api/v1
    resource: 'Dynamic'
    methods: [GET]
    host: iambuying.eu
    schemes: [http]
    type: directory
    requirements:
        _format: 'application/json'
