app_static:
  prefix: /
  resource: '../Static/'
  methods: [GET]
  host: goiwouldlike.com
  schemes: [http]
  type: directory
  requirements:
    _format: 'text/html'
    _locale: en|es|fr|it|ga|pl|cs|sk|de

app_dynamic:
  prefix: /api/v1
  resource: '../Dynamic'
  host: goiwouldlike.com
  schemes: [http]
  type: directory
  requirements:
    _format: 'application/json'