parameters:
    ebay_finding_api_metadata:
        base_url: http://svcs.ebay.com/services/search/FindingService/v1?
        names:
            operation_name: OPERATION-NAME
            service_version: SERVICE-VERSION
            security_appname: SECURITY-APPNAME
            response_data_format: RESPONSE-DATA-FORMAT
            rest_payload: REST-PAYLOAD
        params:
            rest_payload: null
            security_appname: MarioSkr-iwant-SBX-2b0f69f57-865f416d

services:
    _defaults:
        autowire: true
        public: true

    App\Ebay\:
        resource: '../src/Ebay/*'
        exclude: '../src/Ebay/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Tools/*,Library/Type/*,Library/RequestProducer.php}'

    App\Library\:
        resource: '../src/Library'
        exclude: '../src/Library'

    App\Ebay\Library\RequestBase:
        arguments:
            $ebayFindingApiMetadata: '%ebay_finding_api_metadata%'

