parameters:
    marketplaces:
        ebay: Ebay
        amazon: Amazon
        etsy: Etsy

    google_translation_api_id: '103091491679748249212'

    translation_centers:
        - google_translation_center
        - yandex_translation_center

    slack:
        webhooksMap:
            - { channel: '#http_exceptions', webhook: 'https://hooks.slack.com/services/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' }
            - { channel: '#app_activity', webhook: 'https://hooks.slack.com/services/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' }
            - { channel: '#finding_api_limit', webhook: 'https://hooks.slack.com/services/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' }
            - { channel: '#shopping_api_limit', webhook: 'https://hooks.slack.com/services/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' }
            - { channel: '#translations_api', webhook: 'https://hooks.slack.com/services/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' }

    ebay_pagination_limit: 80

    ebay_site_lang_locale_mapping:
        'EBAY-DE': { locale: de, mainLocale: en }
        'EBAY-AT': { locale: de, mainLocale: en }
        'EBAY-ES': { locale: es, mainLocale: en }
        'EBAY-FR': { locale: fr, mainLocale: en }
        'EBAY-FRBE': { locale: fr, mainLocale: en }
        'EBAY-GB': { locale: en, mainLocale: en }
        'EBAY-IT': { locale: it, mainLocale: en }
        'EBAY-US': { locale: en, mainLocale: en }
        'EBAY-IE': { locale: en, mainLocale: en }
        'EBAY-PL': { locale: pl, mainLocale: en }

    yandex_api:
        base_url: 'https://translate.yandex.net/api/v1.5/tr.json/'
        api_key: 'trnsl.1.1.20180912T230845Z.385e471f09d252da.72bd0b5596d99b9fd3fe319bcb1c55c0462f6bf0'
        names:
            ui: ui

    ebay_finding_api_metadata:
        base_url: http://svcs.ebay.com/services/search/FindingService/v1?
        names:
            operation_name: OPERATION-NAME
            security_appname: SECURITY-APPNAME
            response_data_format: RESPONSE-DATA-FORMAT
            rest_payload: REST-PAYLOAD
            service_version: SERVICE-VERSION
            global_id: GLOBAL-ID
        params:
            response_data_format: 'XML'
            service_version: '1.13.0'
            rest_payload: null
            security_appname: MarioSkr-iwant-PRD-aed62ccbf-6c03b3f4

    ebay_shopping_api_metadata:
        base_url: http://open.api.ebay.com/shopping?
        names:
            app_id: appid
            version: version
            response_encoding: responseencoding
        params:
            app_id: MarioSkr-iwant-PRD-aed62ccbf-6c03b3f4
            version: "1081"
            response_encoding: XML

    amazon_product_advertising_api_metadata:
        base_url: http://webservices.amazon
        private_key: '1234567890'
        names:
            service: Service
            operation: Operation
            aws_access_key: AWSAccessKeyId
            associate_tag: AssociateTag
            search_index: SearchIndex
            timestamp: Timestamp
            version: Version
        params:
            service: AWSECommerceService
            aws_access_key: 'access_key_stub_to_be_replaced'
            associate_tag: 'iwouldlike855-21'
            version: '2013-08-01'

    etsy_api:
        base_url: https://openapi.etsy.com/v2
        api_key: 'arz83jklcrhy8o1b2wfrbzuj'
        names:
            api_key: api_key

    bonanza_api:
        base_url: 'https://api.bonanza.com/api_requests/standard_request'
        names:
            dev_name: 'X-BONANZLE-API-DEV-NAME'
        params:
            dev_name: 'Nx901rIYSgvm2po'

    locale: 'en'

    search_component_batch_requests_num: 3

    single_item_cache_ttl: 86400
    search_response_cache_ttl: 86400
    item_translation_cache_ttl: 86400
    shipping_costs_cache_ttl: 86400
    keyword_translation_cache_ttl: 108000

    browser_single_item_cache_ttl: 86400
    browser_search_response_cache_ttl: 86400
    browser_item_translation_cache_ttl: 86400
    browser_shipping_costs_cache_ttl: 86400
    browser_keyword_translation_cache_ttl: 108000

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    BlueDot\BlueDot:
        factory: 'App\Symfony\BlueDot\BlueDotFactory:createBlueDot'
        arguments: ['%kernel.project_dir%', '@doctrine']

    App\Ebay\:
        resource: '../src/Ebay/*'
        exclude: '../src/Ebay/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Tools/*,Library/Type/*,Library/Response/*,Library/Processor/*,Library/RequestProducer.php,Presentation/FindingApi/Model,Presentation/Model,Presentation/ShoppingApi/Model,Business/Request/*,Library/Exception/*}'

    App\Yandex\:
        resource: '../src/Yandex/*'
        exclude: '../src/Yandex/{Library/Processor/*,Presentation/Model/*,Business/Request/*,Library/RequestProducer.php,Library/Model/*,Library/Exception/*}'

    App\App\:
        resource: '../src/App/*'
        exclude: '../src/App/{Presentation/Model/*,Business/Middleware/MiddlewareResult.php}'

    App\App\Business\Finder:
        arguments:
            $router: '@router'

    App\Library\:
        resource: '../src/Library'
        exclude: '../src/Library'

    App\Symfony\:
        resource: '../src/Symfony'
        exclude: '../src/Symfony/{Exception/*,Resolver/*}'

    App\Translation\:
        resource: '../src/Translation'
        exclude: '../src/Translation/Model/*'

    App\Web\:
        resource: '../src/Web'
        exclude: '../src/Web/{Model/*,Grouping/*}'

    App\Web\Library\ResponseEnvironmentHandler:
        arguments:
            $browserSingleItemCacheTtl: '%browser_single_item_cache_ttl%'
            $browserSearchResponseCacheTtl: '%browser_search_response_cache_ttl%'
            $browserItemTranslationCacheTtl: '%browser_item_translation_cache_ttl%'
            $browserKeywordTranslationCacheTtl: '%browser_keyword_translation_cache_ttl%'

    App\Translation\GoogleTranslationCenter:
        arguments:
            $googleTranslationApiId: '%google_translation_api_id%'

    App\Translation\TranslationCenter:
        factory: 'App\Translation\TranslationCenterFactory:createTranslationCenter'
        arguments: ['@App\Translation\GoogleCacheableTranslationCenter', '@App\Translation\YandexCacheableTranslationCenter', '@App\Library\Util\Environment']

    App\Translation\TranslationCenterSwitcher:
        arguments:
            $translationCenters: '%translation_centers%'

    App\Library\Http\HttpCommunicator:

    App\Library\Http\Response\ApiSDK:

    App\Library\Slack\:
        resource: '../src/Library/Slack'
        exclude: '../src/Library/Slack/Metadata.php'

    App\Library\Slack\Config:
        arguments:
            $config: '%slack%'

    # REPRESENTATIONS

    App\Library\Representation\MarketplaceRepresentation:
        arguments:
            $marketplaces: '%marketplaces%'

    App\Library\Representation\LanguageTranslationsRepresentation:
        arguments:
            $ebaySiteLanguageLocaleMapping: '%ebay_site_lang_locale_mapping%'

    App\Library\Representation\MainLocaleRepresentation:
        arguments:
            $mainLocale: '%locale%'

    # REQUEST BASE PROCESSORS
    App\Ebay\Library\Processor\FindingApiRequestBaseProcessor:
        arguments:
            $ebayFindingApiMetadata: '%ebay_finding_api_metadata%'

    App\Ebay\Library\Processor\ShoppingApiRequestBaseProcessor:
        arguments:
            $ebayShoppingApiMetadata: '%ebay_shopping_api_metadata%'

    App\Yandex\Library\Processor\ApiKeyProcessor:
        arguments:
            $yandexApi: '%yandex_api%'

    App\Yandex\Library\Processor\RequestBaseProcessor:
        arguments:
            $yandexApi: '%yandex_api%'

    # HTTP REPOSITORY
    App\Ebay\Source\Repository\FindingApiRepository:
        arguments:
            $communicator: '@App\Ebay\Source\GenericHttpCommunicator'

    App\Yandex\Source\Repository\Repository:
        arguments:
            $env: '%env(APP_ENV)%'
            $communicator: '@App\Yandex\Source\GenericHttpCommunicator'

    # CACHE

    App\Cache\:
        resource: '../src/Cache'

    App\Cache\Cache\SingleProductItemCache:
        arguments:
            $cacheTtl: '%single_item_cache_ttl%'

    App\Cache\Cache\SearchResponseCache:
        arguments:
            $cacheTtl: '%search_response_cache_ttl%'

    App\Cache\Cache\ItemTranslationCache:
        arguments:
            $cacheTtl: '%item_translation_cache_ttl%'

    App\Cache\Cache\KeywordTranslationCache:
        arguments:
            $cacheTtl: '%keyword_translation_cache_ttl%'

    App\Cache\Cache\ShippingCostsTranslationCache:
        arguments:
            $cacheTtl: '%shipping_costs_cache_ttl%'

    App\Cache\Cache\ShippingCostsCache:
        arguments:
            $cacheTtl: '%shipping_costs_cache_ttl%'

    # SYMFONY

    # UTIL
    App\Library\Util\Environment:
        arguments:
            $env: '%env(APP_ENV)%'

    App\Library\Util\SlackImplementation:

    app.symfony.resolver.ebay_search_model_resolver:
        class: 'App\Symfony\Resolver\EbaySearchModelResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    app.symfony.resolver.single_item_resolver:
        class: 'App\Symfony\Resolver\SingleItemRequestModelResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    app.symfony.resolver.acitivity_message_resolver:
        class: 'App\Symfony\Resolver\ActivityMessageResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    app.symfony.resolver.single_item_options_model:
        class: 'App\Symfony\Resolver\SingleItemOptionsModelResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    app.symfony.resolver.single_item_request_model:
        class: 'App\Symfony\Resolver\SingleItemRequestModelResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    app.symfony.resolver.shipping_costs_resolver:
        class: 'App\Symfony\Resolver\ShippingCostsItemResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    # CONTROLLER

    App\Web\Controller\:
        resource: '../src/Web/Controller'
        tags: ['controller.service_arguments']

    # COMPONENT SYSTEM

    App\Component\:
        resource: '../src/Component'
        exclude: '../src/Component/{Search/Ebay/Model/*,Search/Ebay/Business/Factory/Metadata/*,Search/Ebay/Business/ResultHandling/HandledResult.php}'

    App\Component\Search\Ebay\Business\ResultsFetcher\Fetcher\DoubleLocaleSearchFetcher:
        arguments:
            $translationCenter: "@=container.getParameter('kernel.environment') === 'prod' ? service('App\\\\Translation\\\\GoogleCacheableTranslationCenter') : service('App\\\\Translation\\\\YandexCacheableTranslationCenter')"

    App\Component\Search\Ebay\Business\Factory\EbayModelFactory:
        arguments:
            $batchModels: '%search_component_batch_requests_num%'

    # EVENT LISTENER

    App\Symfony\Listener\ExternalApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 300 }

    App\Symfony\Listener\EbayExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 300 }

    App\Symfony\Listener\YandexExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 300 }

    App\Symfony\Listener\SystemExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 0 }

    App\Symfony\Listener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # REPOSITORY
    App\Doctrine\Repository\CountryRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\SingleProductItemRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\SearchCacheRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\IpAddressRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\ItemTranslationCacheRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\KeywordTranslationCacheRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\TranslationCenterSwitchRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\EbayBusinessEntityRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\TextLocaleIdentifierRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\ShippingCostsTranslationCacheRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\ShippingCostsItemRepository:
        arguments:
            $registry: '@doctrine'

    # COMMANDS

    App\Symfony\Command\PopulateCountries:
        arguments:
            $httpCommunicator: '@App\Library\Http\HttpCommunicator'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\Util\ViewUserProfile:
        arguments:
            $finder: '@App\Ebay\Business\Finder'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\Util\YandexSupportedLanguages:
        arguments:
            $yandexEntryPoint: '@App\Yandex\Presentation\EntryPoint\YandexEntryPoint'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\CompleteCacheRemove:
        arguments:
            $doctrine: '@doctrine'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\GetFindingApiVersion:
        arguments:
            $findingApiEntryPoint: '@App\Ebay\Presentation\FindingApi\EntryPoint\FindingApiEntryPoint'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\TranslationCenterSwitcher:
        arguments:
            $translationCenters: '%translation_centers%'
        tags:
            - { name: 'console.command' }