parameters:
    ebay_finding_api_metadata:
        base_url: http://svcs.ebay.com/services/search/FindingService/v1?
        names:
            operation_name: OPERATION-NAME
            security_appname: SECURITY-APPNAME
            response_data_format: RESPONSE-DATA-FORMAT
            rest_payload: REST-PAYLOAD
            service_version: SERVICE-VERSION
        params:
            response_data_format: 'XML'
            service_version: '1.0.0'
            rest_payload: null
            security_appname: MarioSkr-iwant-PRD-aed62ccbf-6c03b3f4
    amazon_product_advertising_api_metadata:
        base_url: http://webservices.amazon
        private_key: '1234567890'
        names:
            service: Service
            operation: Operation
            aws_access_key: AWSAccessKeyId
            associate_tag: AssociateTag
            search_index: SearchIndex
            timestamp: Timestamp
            version: Version
        params:
            service: AWSECommerceService
            aws_access_key: 'access_key_stub_to_be_replaced'
            associate_tag: 'iwouldlike855-21'
            version: '2013-08-01'
    etsy_api:
        base_url: https://openapi.etsy.com/v2
        api_key: 'arz83jklcrhy8o1b2wfrbzuj'
        names:
            api_key: api_key

    bonanza_api:
        base_url: 'https://api.bonanza.com/api_requests/standard_request'
        names:
            dev_name: 'X-BONANZLE-API-DEV-NAME'
        params:
            dev_name: 'Nx901rIYSgvm2po'

services:
    _defaults:
        autowire: true
        public: true

    App\Amazon\:
        resource: '../src/Amazon/*'
        exclude: '../src/Amazon/{Library/*,Presentation/ProductAdvertising/Model/*}'

    App\Ebay\:
        resource: '../src/Ebay/*'
        exclude: '../src/Ebay/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Tools/*,Library/Type/*,Library/Response/*,Library/Processor/*,Library/RequestProducer.php,Presentation/FindingApi/Model,Business/Request/*}'

    App\Etsy\:
        resource: '../src/Etsy/*'
        exclude: '../src/Etsy/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Processor/*,Library/RequestProducer.php,Request.php,Presentation/Model/*,Library/Response/*,Business/Request/*}'

    App\Bonanza\:
        resource: '../src/Bonanza/*'
        exclude: '../src/Bonanza/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Type/*,Library/Processor/*,Library/RequestProducer.php,Library/Request.php,Presentation/Model/*,Library/Response/*}'

    App\Library\:
        resource: '../src/Library'
        exclude: '../src/Library'

    App\Symfony\:
        resource: '../src/Symfony'
        exclude: '../src/Symfony/{Exception/*}'

    App\Library\Tools\MemcachedWrapper:

    # REQUEST BASE PROCESSORS
    App\Ebay\Library\Processor\RequestBaseProcessor:
        arguments:
            $ebayFindingApiMetadata: '%ebay_finding_api_metadata%'

    App\Amazon\Library\Processor\RequestBaseProcessor:
        arguments:
            $amazonProductAdvertisingApiMetadata: '%amazon_product_advertising_api_metadata%'

    App\Etsy\Library\Processor\RequestBaseProcessor:
        arguments:
            $etsyApi: '%etsy_api%'

    App\Etsy\Library\Processor\ApiKeyProcessor:
        arguments:
            $etsyApi: '%etsy_api%'

    App\Bonanza\Library\Processor\RequestBaseProcessor:
        arguments:
            $bonanzaApi: '%bonanza_api%'

    App\Bonanza\Library\Processor\ApiKeyPostHeaderProcessor:
        arguments:
            $bonanzaApi: '%bonanza_api%'

    # REPOSITORY
    App\Ebay\Source\Repository\FindingApiRepository:
        arguments:
            $env: '%env(APP_ENV)%'
            $communicator: '@App\Ebay\Source\GenericHttpCommunicator'

    App\Etsy\Source\Repository\EtsyRepository:
        arguments:
            $env: '%env(APP_ENV)%'
            $communicator: '@App\Etsy\Source\GenericHttpCommunicator'

    App\Bonanza\Source\Repository\BonanzaRepository:
        arguments:
            $env: '%env(APP_ENV)%'
            $communicator: '@App\Bonanza\Source\GenericHttpCommunicator'

    # SYMFONY

    # EVENT LISTENER

    App\Symfony\Listener\HttpExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }