parameters:
    marketplaces:
        ebay: Ebay
        amazon: Amazon
        etsy: Etsy
        viagogo: Viagogo
        ticketMaster: ticketmaster

    yandex_translation_languages:
        'EBAY-DE': en
        'EBAY-NL': en
        'EBAY-FR': en

    yandex_api:
        base_url: 'https://translate.yandex.net/api/v1.5/tr.json/'
        api_key: 'trnsl.1.1.20180912T230845Z.385e471f09d252da.72bd0b5596d99b9fd3fe319bcb1c55c0462f6bf0'
        names:
            ui: ui

    ebay_finding_api_metadata:
        base_url: http://svcs.ebay.com/services/search/FindingService/v1?
        names:
            operation_name: OPERATION-NAME
            security_appname: SECURITY-APPNAME
            response_data_format: RESPONSE-DATA-FORMAT
            rest_payload: REST-PAYLOAD
            service_version: SERVICE-VERSION
            global_id: GLOBAL-ID
        params:
            response_data_format: 'XML'
            service_version: '1.0.0'
            rest_payload: null
            security_appname: MarioSkr-iwant-PRD-aed62ccbf-6c03b3f4

    ebay_shopping_api_metadata:
        base_url: http://open.api.ebay.com/shopping?
        names:
            app_id: appid
            version: version
            response_encoding: responseencoding
            site_id: siteiD
        params:
            app_id: MarioSkr-iwant-PRD-aed62ccbf-6c03b3f4
            version: "1063"
            response_encoding: XML
            site_id: "3"
    amazon_product_advertising_api_metadata:
        base_url: http://webservices.amazon
        private_key: '1234567890'
        names:
            service: Service
            operation: Operation
            aws_access_key: AWSAccessKeyId
            associate_tag: AssociateTag
            search_index: SearchIndex
            timestamp: Timestamp
            version: Version
        params:
            service: AWSECommerceService
            aws_access_key: 'access_key_stub_to_be_replaced'
            associate_tag: 'iwouldlike855-21'
            version: '2013-08-01'
    etsy_api:
        base_url: https://openapi.etsy.com/v2
        api_key: 'arz83jklcrhy8o1b2wfrbzuj'
        names:
            api_key: api_key

    bonanza_api:
        base_url: 'https://api.bonanza.com/api_requests/standard_request'
        names:
            dev_name: 'X-BONANZLE-API-DEV-NAME'
        params:
            dev_name: 'Nx901rIYSgvm2po'

services:
    _defaults:
        autowire: true
        public: true

    BlueDot\BlueDot:
        factory: 'App\Symfony\BlueDot\BlueDotFactory:createBlueDot'
        arguments: ['%kernel.project_dir%', '@doctrine']

    App\Amazon\:
        resource: '../src/Amazon/*'
        exclude: '../src/Amazon/{Library/*,Presentation/ProductAdvertising/Model/*}'

    App\Ebay\:
        resource: '../src/Ebay/*'
        exclude: '../src/Ebay/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Tools/*,Library/Type/*,Library/Response/*,Library/Processor/*,Library/RequestProducer.php,Presentation/FindingApi/Model,Presentation/Model,Presentation/ShoppingApi/Model,Business/Request/*}'

    App\Etsy\:
        resource: '../src/Etsy/*'
        exclude: '../src/Etsy/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Processor/*,Library/RequestProducer.php,Request.php,Presentation/Model/*,Library/Response/*,Business/Request/*}'

    App\Bonanza\:
        resource: '../src/Bonanza/*'
        exclude: '../src/Bonanza/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Type/*,Library/Processor/*,Library/RequestProducer.php,Library/Request.php,Presentation/Model/*,Library/Response/*}'

    App\Yandex\:
        resource: '../src/Yandex/*'
        exclude: '../src/Yandex/{Library/Processor/*,Presentation/Model/*,Business/Request/*,Library/RequestProducer.php,Library/Response/*}'

    App\App\:
        resource: '../src/App/*'
        exclude: '../src/App/{Presentation/Model/*}'

    App\Library\:
        resource: '../src/Library'
        exclude: '../src/Library'

    App\Symfony\:
        resource: '../src/Symfony'
        exclude: '../src/Symfony/{Exception/*,Resolver/*}'

    App\Library\Tools\MemcachedWrapper:

    App\Library\Http\HttpCommunicator:

    App\Library\Http\Response\ApiSDK:

    # REPRESENTATIONS

    App\Library\Representation\ShopsRepresentation:
        arguments:
            $nativeTaxonomyRepository: '@App\Doctrine\Repository\NativeTaxonomyRepository'
            $marketplaceRepresentation: '@App\Library\Representation\MarketplaceRepresentation'

    App\Library\Representation\MarketplaceRepresentation:
        arguments:
            $marketplaces: '%marketplaces%'

    App\Library\Representation\NativeTaxonomyRepresentation:
        arguments:
            $nativeTaxonomyRepository: '@App\Doctrine\Repository\NativeTaxonomyRepository'

    App\Library\Representation\LanguageTranslationsRepresentation:
        arguments:
            $yandexTranslationLanguages: '%yandex_translation_languages%'

    App\Library\Representation\ApplicationShopRepresentation:
        arguments:
            $applicationShopRepository: '@App\Doctrine\Repository\ApplicationShopRepository'

    # REQUEST BASE PROCESSORS
    App\Ebay\Library\Processor\FindingApiRequestBaseProcessor:
        arguments:
            $ebayFindingApiMetadata: '%ebay_finding_api_metadata%'

    App\Ebay\Library\Processor\ShoppingApiRequestBaseProcessor:
        arguments:
            $ebayShoppingApiMetadata: '%ebay_shopping_api_metadata%'

    App\Amazon\Library\Processor\RequestBaseProcessor:
        arguments:
            $amazonProductAdvertisingApiMetadata: '%amazon_product_advertising_api_metadata%'

    App\Etsy\Library\Processor\RequestBaseProcessor:
        arguments:
            $etsyApi: '%etsy_api%'

    App\Etsy\Library\Processor\ApiKeyProcessor:
        arguments:
            $etsyApi: '%etsy_api%'

    App\Bonanza\Library\Processor\RequestBaseProcessor:
        arguments:
            $bonanzaApi: '%bonanza_api%'

    App\Bonanza\Library\Processor\ApiKeyPostHeaderProcessor:
        arguments:
            $bonanzaApi: '%bonanza_api%'

    App\Yandex\Library\Processor\ApiKeyProcessor:
        arguments:
            $yandexApi: '%yandex_api%'

    App\Yandex\Library\Processor\RequestBaseProcessor:
        arguments:
            $yandexApi: '%yandex_api%'

    # REPOSITORY
    App\Ebay\Source\Repository\FindingApiRepository:
        arguments:
            $env: '%env(APP_ENV)%'
            $communicator: '@App\Ebay\Source\GenericHttpCommunicator'

    App\Etsy\Source\Repository\EtsyRepository:
        arguments:
            $env: '%env(APP_ENV)%'
            $communicator: '@App\Etsy\Source\GenericHttpCommunicator'

    App\Bonanza\Source\Repository\BonanzaRepository:
        arguments:
            $env: '%env(APP_ENV)%'
            $communicator: '@App\Bonanza\Source\GenericHttpCommunicator'

    App\Yandex\Source\Repository\Repository:
        arguments:
            $env: '%env(APP_ENV)%'
            $communicator: '@App\Yandex\Source\GenericHttpCommunicator'

    # CACHE

    App\Cache\:
        resource: '../src/Cache'

    # SYMFONY

    # RESOLVER
    app.symfony.resolver.todays_products_resolver:
        class: 'App\Symfony\Resolver\TodaysProductsModelResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    app.symfony.resolver.search_model_resolver:
        class: 'App\Symfony\Resolver\SearchModelResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    app.symfony.resolver.single_item_resolver:
        class: 'App\Symfony\Resolver\SingleItemRequestModelResolver'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    # CONTROLLER

    App\Web\:
        resource: '../src/Web'
        exclude: '../src/Web/{Model/*,Grouping/*}'

    App\Web\Controller\:
        resource: '../src/Web/Controller'
        tags: ['controller.service_arguments']

    # COMPONENT SYSTEM

    App\Component\:
        resource: '../src/Component'
        exclude: '../src/Component/{TodayProducts/Model/*,TodayProducts/Request/Model/*,TodayProducts/Selector/Ebay/Selector/*,TodayProducts/Selector/Etsy/Selector/*,Search/Ebay/Model/*,Search/Ebay/Business/Factory/Metadata/*}'

    App\Component\Search\Ebay\Business\Finder:
        arguments:
            $env: '%env(APP_ENV)%'
            $nexySlack: '@nexy_slack.client'
    # EVENT LISTENER

    App\Symfony\Listener\HttpExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # REPOSITORY
    App\Doctrine\Repository\RequestCacheRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\CountryRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\NativeTaxonomyRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\EbayRootCategoryRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\ApplicationShopRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\TodaysProductsCacheRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\ToggleCacheRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\SingleProductItemRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\SearchRequestRepository:
        arguments:
            $registry: '@doctrine'

    App\Doctrine\Repository\SearchCacheRepository:
        arguments:
            $registry: '@doctrine'

    # COMMANDS

    App\Symfony\Command\PopulateCountries:
        arguments:
            $httpCommunicator: '@App\Library\Http\HttpCommunicator'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\LoadProductsFromEbayStore:
        arguments:
            $finder: '@App\Ebay\Business\Finder'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\GetUserProfile:
        arguments:
            $finder: '@App\Ebay\Business\Finder'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\UpsertNativeTaxonomy:
        arguments:
            $nativeTaxonomyRepository: '@App\Doctrine\Repository\NativeTaxonomyRepository'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\CategoryConnection\ConnectEbayCategories:
        arguments:
            $nativeTaxonomyRepository: '@App\Doctrine\Repository\NativeTaxonomyRepository'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\CreateNativeShops:
        arguments:
            $shoppingApiEntryPoint: '@App\Ebay\Presentation\ShoppingApi\EntryPoint\ShoppingApiEntryPoint'
            $nativeTaxonomyRepository: '@App\Doctrine\Repository\NativeTaxonomyRepository'
            $applicationShopRepository: '@App\Doctrine\Repository\ApplicationShopRepository'
            $shopsRepresentation: '@App\Library\Representation\ShopsRepresentation'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\InvalidateRequestCache:
        arguments:
            $requestCacheRepository: '@App\Doctrine\Repository\RequestCacheRepository'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\ToggleCache:
        arguments:
            $toggleCacheRepository: '@App\Doctrine\Repository\ToggleCacheRepository'
        tags:
        - { name: 'console.command' }

    App\Symfony\Command\InitialCacheToggle:
        arguments:
            $toggleCacheRepository: '@App\Doctrine\Repository\ToggleCacheRepository'
        tags:
            - { name: 'console.command' }

    App\Symfony\Command\StaleRequestCacheRemove:
        arguments:
            $apiRequestCache: '@App\Cache\Cache\ApiRequestCache'
            $blueDot: '@BlueDot\BlueDot'
        tags:
        - { name: 'console.command' }