parameters:
    marketplaces:
        ebay: Ebay
        amazon: Amazon
        etsy: Etsy

    translation_centers:
        - google_translation_center
        - yandex_translation_center

    yandex_translation_languages:
        'EBAY-DE': en
        'EBAY-NL': en
        'EBAY-FR': en

    yandex_api:
        base_url: 'https://translate.yandex.net/api/v1.5/tr.json/'
        api_key: 'trnsl.1.1.20180912T230845Z.385e471f09d252da.72bd0b5596d99b9fd3fe319bcb1c55c0462f6bf0'
        names:
            ui: ui

    ebay_finding_api_metadata:
        base_url: http://svcs.ebay.com/services/search/FindingService/v1?
        names:
            operation_name: OPERATION-NAME
            security_appname: SECURITY-APPNAME
            response_data_format: RESPONSE-DATA-FORMAT
            rest_payload: REST-PAYLOAD
            service_version: SERVICE-VERSION
            global_id: GLOBAL-ID
        params:
            response_data_format: 'XML'
            service_version: '1.13.0'
            rest_payload: null
            security_appname: MarioSkr-iwant-PRD-aed62ccbf-6c03b3f4

    ebay_shopping_api_metadata:
        base_url: http://open.api.ebay.com/shopping?
        names:
            app_id: appid
            version: version
            response_encoding: responseencoding
            site_id: siteid
        params:
            app_id: MarioSkr-iwant-PRD-aed62ccbf-6c03b3f4
            version: "1081"
            response_encoding: XML
            site_id: "0"

    amazon_product_advertising_api_metadata:
        base_url: http://webservices.amazon
        private_key: '1234567890'
        names:
            service: Service
            operation: Operation
            aws_access_key: AWSAccessKeyId
            associate_tag: AssociateTag
            search_index: SearchIndex
            timestamp: Timestamp
            version: Version
        params:
            service: AWSECommerceService
            aws_access_key: 'access_key_stub_to_be_replaced'
            associate_tag: 'iwouldlike855-21'
            version: '2013-08-01'

    etsy_api:
        base_url: https://openapi.etsy.com/v2
        api_key: 'arz83jklcrhy8o1b2wfrbzuj'
        names:
            api_key: api_key

    bonanza_api:
        base_url: 'https://api.bonanza.com/api_requests/standard_request'
        names:
            dev_name: 'X-BONANZLE-API-DEV-NAME'
        params:
            dev_name: 'Nx901rIYSgvm2po'

    single_item_cache_ttl: 86400
    search_response_cache_ttl: 86400
    item_translation_cache_ttl: 86400
    shipping_costs_cache_ttl: 86400
    keyword_translation_cache_ttl: 108000

    added_something: 1000

    browser_single_item_cache_ttl: 86400
    browser_search_response_cache_ttl: 86400
    browser_item_translation_cache_ttl: 86400
    browser_shipping_costs_cache_ttl: 86400
    browser_keyword_translation_cache_ttl: 108000

    search_component_batch_requests_num: 1

services:
    _defaults:
        autowire: true
        public: true

    # APPLICATION

    App\Ebay\:
        resource: '../src/Ebay/*'
        exclude: '../src/Ebay/{Library/Dynamic/*,Library/Information/*,Library/ItemFilter/*,Library/Tools/*,Library/Type/*,Library/Response/*,Library/Processor/*,Library/RequestProducer.php,Presentation/FindingApi/Model,Presentation/Model,Presentation/ShoppingApi/Model,Business/Request/*,Library/Exception/*}'

    App\Yandex\:
        resource: '../src/Yandex/*'
        exclude: '../src/Yandex/{Library/Processor/*,Presentation/Model/*,Business/Request/*,Library/RequestProducer.php,Library/Model/*,Library/Exception/*}'

    App\App\:
        resource: '../src/App/*'
        exclude: '../src/App/{Presentation/Model/*,Business/Middleware/MiddlewareResult.php}'

    App\App\Business\Finder:
        arguments:
            $router: '@router'

    App\App\Library\Representation\SiteLocaleMappingRepresentation:
        arguments:
            $mapping: '%ebay_site_lang_locale_mapping%'

    App\Library\:
        resource: '../src/Library'
        exclude: '../src/Library'

    App\Symfony\:
        resource: '../src/Symfony'
        exclude: '../src/Symfony/{Exception/*,Resolver/*}'

    App\Web\:
        resource: '../src/Web'
        exclude: '../src/Web/{Model/*,Grouping/*}'

    App\Web\Library\ResponseEnvironmentHandler:
        arguments:
            $browserSingleItemCacheTtl: '%browser_single_item_cache_ttl%'
            $browserSearchResponseCacheTtl: '%browser_search_response_cache_ttl%'
            $browserItemTranslationCacheTtl: '%browser_item_translation_cache_ttl%'
            $browserKeywordTranslationCacheTtl: '%browser_keyword_translation_cache_ttl%'

  # COMPONENT SYSTEM

    App\Component\:
        resource: '../src/Component'
        exclude: '../src/Component/{Search/Ebay/Model/*,Search/Ebay/Business/Factory/Metadata/*,Search/Etsy/Model/*,Search/Ebay/Business/ResultHandling/HandledResult.php}'

    App\Component\Search\Ebay\Business\ResultsFetcher\Fetcher\DoubleLocaleSearchFetcher:
        arguments:
            $translationCenter: "@=container.getParameter('kernel.environment') === 'prod' ? service('App\\\\Translation\\\\GoogleTranslationCenter') : service('App\\\\Translation\\\\YandexTranslationCenter')"

    App\Component\Search\Ebay\Business\Factory\EbayModelFactory:
        arguments:
            $batchModels: '%search_component_batch_requests_num%'


    # REQUEST BASE PROCESSORS
    App\Ebay\Library\Processor\FindingApiRequestBaseProcessor:
        arguments:
            $ebayFindingApiMetadata: '%ebay_finding_api_metadata%'

    App\Ebay\Library\Processor\ShoppingApiRequestBaseProcessor:
        arguments:
            $ebayShoppingApiMetadata: '%ebay_shopping_api_metadata%'

    App\Yandex\Library\Processor\RequestBaseProcessor:
        arguments:
            $yandexApi: '%yandex_api%'

    # HTTP REPOSITORY
    App\Ebay\Source\Repository\FindingApiRepository:
        arguments:
            $communicator: '@App\Ebay\Source\GenericHttpCommunicator'

    App\Yandex\Source\Repository\Repository:
      arguments:
        $env: '%env(APP_ENV)%'
        $communicator: '@App\Yandex\Source\GenericHttpCommunicator'

    # CACHE

    App\Cache\:
        resource: '../src/Cache'

    App\Cache\Cache\SingleProductItemCache:
        arguments:
            $cacheTtl: '%single_item_cache_ttl%'

    App\Cache\Cache\SearchResponseCache:
        arguments:
            $cacheTtl: '%search_response_cache_ttl%'

    App\Cache\Cache\ItemTranslationCache:
        arguments:
            $cacheTtl: '%item_translation_cache_ttl%'

    App\Cache\Cache\KeywordTranslationCache:
        arguments:
            $cacheTtl: '%keyword_translation_cache_ttl%'

    App\Cache\Cache\ShippingCostsTranslationCache:
        arguments:
            $cacheTtl: '%shipping_costs_cache_ttl%'

    App\Cache\Cache\ShippingCostsCache:
        arguments:
            $cacheTtl: '%shipping_costs_cache_ttl%'

    # DATA PROVIDERS
    App\Tests\Ebay\FindingApi\DataProvider\:
        resource: '../tests/Ebay/FindingApi/DataProvider'
        exclude: '../tests/Ebay/FindingApi/DataProvider/*'

    data_provider.finding_api:
        class: App\Tests\Ebay\FindingApi\DataProvider\DataProvider
        autowire: false

    data_provider.shopping_api:
        class: App\Tests\Ebay\ShoppingApi\DataProvider\DataProvider

    data_provider.component:
        class: App\Tests\Component\DataProvider\DataProvider

    data_provider.app:
        class: App\Tests\App\DataProvider\DataProvider

    data_provider.component.yandex:
        class: App\Tests\Yandex\DataProvider\DataProvider

    # SYMFONY

    # EVENT LISTENER

    App\Symfony\Listener\ExternalApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 300 }

    App\Symfony\Listener\EbayExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 300 }

    App\Symfony\Listener\SystemExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 0 }

    App\Symfony\Listener\YandexExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 300 }

    App\Symfony\Listener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    App\Symfony\Command\TranslationCenterSwitcher:
        arguments:
            $translationCenters: '%translation_centers%'
        tags:
            - { name: 'console.command' }


