app_get_todays_products:
  path: /get-todays-products
  controller: App\Web\Controller\TodayProductsController::getTodaysProducts

app_get_item:
  path: /item/{marketplace}/{itemId}
  controller: App\Web\Controller\AppController::getSingleItem

app_get_countries:
  path: /get-countries
  controller: App\Web\Controller\AppController:getCountries

app_get_marketplaces:
  path: /get-marketplaces
  controller: App\Web\Controller\AppController:getMarketplaces

app_get_taxonomies:
  path: /get-taxonomies
  controller: App\Web\Controller\AppController:getNativeTaxonomies