app_post_activity_message:
  path: /activity-message
  controller: App\Web\Controller\AppController::postActivity
  methods: [POST]

app_get_countries:
  path: /get-countries
  controller: App\Web\Controller\AppController::getCountries
  methods: [GET]

app_get_marketplaces:
  path: /get-marketplaces
  controller: App\Web\Controller\AppController::getMarketplaces
  methods: [GET]

app_get_products_by_global_id:
  path: /ebay/get-products-by-global-id/{searchData}
  controller: App\Web\Controller\SearchController::getEbayProductsByGlobalId
  methods: [GET]

app_get_taxonomies:
  path: /get-taxonomies
  controller: App\Web\Controller\AppController::getNativeTaxonomies
  methods: [GET]

app_get_ebay_global_id_information:
  path: /get-ebay-global-id-information
  controller: App\Web\Controller\AppController::getGlobalIdsInformation
  methods: [GET]

app_options_check_single_item:
  path: /ebay/check-single-item/{locale}/{itemId}
  controller: App\Web\Controller\QuickLookSingleItemController::optionsCheckSingleItem
  methods: [GET]

app_put_single_item:
  path: /ebay/create-single-item
  controller: App\Web\Controller\QuickLookSingleItemController::putSingleItem
  methods: [PUT]

app_get_quick_look_single_item:
  path: /ebay/get-quick-look-single-item/{locale}/{itemId}
  controller: App\Web\Controller\QuickLookSingleItemController:getSingleItem
  methods: [GET]

app_get_single_item:
  path: /ebay/get-single-item/{locale}/{itemId}
  controller: App\Web\Controller\SingleItemController:getSingleItem
  methods: [GET]